(() => {
  'use strict';

  const aa = a => a
    (a => a => a => a => a => a)
    (a => a
      (a => a
        (a => a
          (a => a
            (a => b => a + b)
            (a => +a))
          (a => a
            (a => !a)
            (a => b => b [a])))
        (a => a
          (a => b => c => c [a] (b))
          (a => [a])))
      (a => a
        (a => b => c => a (c) (b (c)))
        (a => b => a)))

  const ab = aa(aa), ac = aa(ab), ad = ac(ab), ae = ad(ad), af = ad(ae)
      , ag = ad(af), ah = ad(ag), ai = ag(ah), aj = ah(ai), ak = aj(ag)
      , al = ak(ak), am = al(ah), an = ah(am), ao = ag(ag), ap = an(ao)
      , aq = ap(ae), ar = aq(ab), as = aq(ag), at = ac(ag), au = as(at)
      , av = ar(au), aw = ar(av), ax = as(au), ay = as(ax), az = ak(ak)
      , ba = az(aw), bb = ap(ba), bc = ap(ay), bd = bc(ae), be = bb(bd)
      , bf = as(av), bg = bf(ay), bh = bf(bg), bi = ay(bh), bj = bi(bg)
      , bk = ay(bj), bl = bk(bj), bm = bk(bl), bn = be(bm), bo = ay(bg)
      , bp = bo(bg), bq = be(bp), br = bq(bg), bs = ay(br), bt = be(bl)
      , bu = bt(bg), bv = ay(bu), bw = be(bj), bx = bw(bg), by = ay(bx)
      , bz = bq(bh), ca = by(bz), cb = bv(ca), cc = bs(cb), cd = aw(cc)
      , ce = ar(at), cf = ar(ce), cg = aw(bp), ch = cg(bp), ci = cf(ch)
      , cj = cd(ci), ck = bn(cj), cl = ay(ck), cm = bk(bm), cn = bk(cm)
      , co = bk(cn), cp = be(co), cq = cp(cj), cr = ay(cq), cs = be(bj)
      , ct = cs(ch), cu = ay(ct), cv = be(bm), cw = cv(bg), cx = ay(cw)
      , cy = ay(bz), cz = be(bj), da = cz(bh), db = ay(da), dc = be(bl)
      , dd = dc(bh), de = ay(dd), df = ay(ck), dg = ay(bz), dh = ay(cq)
      , di = dh(da), dj = dg(di), dk = df(dj), dl = de(dk), dm = db(dl)
      , dn = cy(dm), dp = cx(dn), dq = cu(dp), dr = cr(dq), ds = cl(dr)
      , dt = aw(ds), du = dt(ae), dv = ap(du), dw = dv(ae), dx = ak(dw)
      , dy = ay(da), dz = be(cm), ea = dz(bg), eb = ay(ea), ec = ay(bz)
      , ed = ay(dd), ee = ay(da), ef = ee(ct), eg = ed(ef), eh = ec(eg)
      , ei = eb(eh), ej = dy(ei), ek = ay(ej), el = ay(br), em = ay(da)
      , en = ay(cq), eo = ah(ay), ep = eo(ae), eq = ep(cm), er = bk(eq)
      , es = bk(er), et = bk(es), eu = be(et), ev = dt(bp), ew = eu(ev)
      , ex = en(ew), ey = em(ex), ez = el(ey), fa = ay(ez), fb = aw(bl)
      , fc = ak(dw), fd = ay(ej), fe = be(eq), ff = dt(ci), fg = fe(ff)
      , fh = fd(fg), fi = ay(fh), fj = fc(fi), fk = ay(ea), fl = ay(cw)
      , fm = ay(ck), fn = ay(bx), fo = aw(bj), fp = as(ce), fq = ay(bz)
      , fr = fq(cq), fs = ay(fr), ft = ay(ct), fu = ay(bx), fv = ay(ew)
      , fw = fv(ea), fx = fu(fw), fy = ft(fx), fz = aw(fy), ga = dt(bx)
      , gb = fz(ga), gc = fs(gb), gd = fp(gc), ge = bk(co), gf = ay(ge)
      , gg = gf(eq), gh = ay(gg), gi = ep(eq), gj = gh(gi), gk = gd(gj)
      , gl = ay(gi), gm = gl(bl), gn = bk(gm), go = ay(gn), gp = ep(gi)
      , gq = ep(gp), gr = ay(gq), gs = ep(gq), gt = gr(gs), gu = go(gt)
      , gv = gk(gu), gw = fo(gv), gx = ay(gw), gy = gx(ea), gz = fn(gy)
      , ha = fm(gz), hb = fl(ha), hc = fk(hb), hd = fj(hc), he = ap(fp)
      , hf = he(ch), hg = be(cn), hh = hg(ch), hi = ay(hh), hj = ay(bz)
      , hk = ay(bx), hl = ay(bu), hm = ay(hh), hn = ay(ck), ho = hn(cw)
      , hp = hm(ho), hq = hl(hp), hr = hk(hq), hs = hj(hr), ht = hi(hs)
      , hu = hf(ht), hv = hf(gc), hw = cf(ch), hx = hv(hw), hy = hu(hx)
      , hz = hd(hy), ia = fb(hz), ib = ay(ia), ic = aw(bj), id = ay(bm)
      , ie = id(gm), ig = gd(ie), ih = ay(cn), ii = ay(gp), ij = ii(gq)
      , ik = ih(ij), il = ig(ik), im = ic(il), io = ay(im), ip = ay(bx)
      , iq = ip(da), ir = io(iq), is = ib(ir), it = ay(is), iu = ay(ia)
      , iv = ay(cq), iw = be(bl), ix = iw(ch), iy = ay(ix), iz = iy(ea)
      , ja = iv(iz), jb = iu(ja), jc = it(jb), jd = fa(jc), je = aw(jd)
      , jf = je(ga), jg = ay(eq), jh = jg(gp), ji = jf(jh), jj = ek(ji)
      , jk = ay(jj), jl = ak(jk), jm = ap(ay), jn = bk(jh), jo = jf(jn)
      , jp = jm(jo), jq = jl(jp), jr = dx(jq), js = ak(jr), jt = ap(ay)
      , ju = ay(eq), jv = ju(ie), jw = ay(jv), jx = jw(gp), jy = jf(jx)
      , jz = ay(jy), ka = bk(jx), kb = jf(ka), kc = jz(kb), kd = jt(kc)
      , ke = kd(bx), kf = ay(ke), kg = ay(bl), kh = kg(ij), ki = jf(kh)
      , kj = kd(ki), kk = kf(kj), kl = ay(kk), km = ak(kl), kn = ay(bx)
      , ko = ak(kn), kp = ap(ay), kq = kp(ki), kr = ko(kq), ks = km(kr)
      , kt = js(ks), ku = ay(cn), kv = ku(jh), kw = jf(kv), kx = kt(kw)
      , ky = kx(gs), kz = ky(cm), la = jf(kz), lb = ep(la), lc = kt(lb)
      , ld = ap(aw), le = ay(bz), lf = ay(im), lg = ay(hh), lh = lg(cw)
      , li = lf(lh), lj = le(li), lk = fj(lj), ll = ld(lk), lm = ay(bx)
      , ln = ay(bu), lo = ay(ea), lp = ay(da), lq = lp(bz), lr = lo(lq)
      , ls = ln(lr), lt = lm(ls), lu = ll(lt), lv = lc(lu), lw = ay(bu)
      , lx = ay(cq), ly = ay(ge), lz = ly(ij), ma = jf(lz), mb = lx(ma)
      , mc = lw(mb), md = aw(mc), me = ay(ck), mf = ay(cq), mg = ay(ct)
      , mh = ay(cw), mi = ay(cq), mj = ay(bu), mk = mj(ea), ml = mi(mk)
      , mm = mh(ml), mn = mg(mm), mo = mf(mn), mp = me(mo), mq = ll(mp)
      , mr = md(mq), ms = lv(mr), mt = ay(fr), mu = kx(lz), mv = mu(bm)
      , mw = kx(mv), mx = mw(gg), my = jf(mx), mz = ay(my), na = ay(gw)
      , nb = ay(gw), nc = ay(ea), nd = nc(da), ne = nb(nd), nf = na(ne)
      , ng = mz(nf), nh = ay(ng), ni = ay(ia), nj = ay(bx), nk = ay(cw)
      , nl = nk(ea), nm = nj(nl), nn = ni(nm), no = nh(nn), np = mt(no)
      , nq = hf(np), nr = nq(im), ns = ay(nr), nt = ay(ea), nu = ay(bu)
      , nv = ay(bu), nw = nv(cq), nx = nu(nw), ny = nt(nx), nz = ns(ny)
      , oa = ay(nz), ob = ay(et), oc = bk(gp), od = ob(oc), oe = jf(od)
      , of = ay(oe), og = of(fg), oh = ay(og), oi = ay(gn), oj = oi(mv)
      , ok = jf(oj), ol = nq(ok), om = ay(ol), on = ay(cq), oo = ay(da)
      , op = ay(bu), oq = op(ix), or = oo(oq), os = on(or), ot = om(os)
      , ou = ay(ot), ov = jf(oc), ow = ou(ov), ox = oh(ow), oy = oa(ox)
      , oz = ms(oy)
})()